### ISSUE TITLE
Android SDK 2.0.0.80 crashes after finishing a phone call.

### ISSUE THREAD

**Issue by mydoal** [oovoodev/Android-SDK-Sample#16]
Using Android SDK 2.0.0.80

The crashes after a phone call ends still happens in this version...

08-10 15:36:13.194    5516-5516/com.xxx E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.xxx, PID: 5516
    java.lang.RuntimeException: Unable to instantiate receiver com.oovoo.core.phone.CallReceiver: java.lang.ClassNotFoundException: Didn't find class "com.oovoo.core.phone.CallReceiver" on path: DexPathList[[zip file "/data/app/com.xxx-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.xxx-2, /vendor/lib, /system/lib]]
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2405)
            at android.app.ActivityThread.access$1700(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1276)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.oovoo.core.phone.CallReceiver" on path: DexPathList[[zip file "/data/app/com.xxx -2.apk"],nativeLibraryDirectories=[/data/app-lib/xxx .-2, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2400)
            at android.app.ActivityThread.access$1700(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1276)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5105)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
            at dalvik.system.NativeStart.main(Native Method)
08-10 15:37:22.174    5516-5522/com.xxx  I/dalvikvm﹕ Debugger is active

**Comment by eakraly** [comment]
Hi @mydoal,
We are aware of the problem and working on a fix.
Expect new version soon.
