### ISSUE TITLE
Crash in Android 6.0 Marshmallow - UnsatisfiedLinkError

### ISSUE THREAD

**Issue by mateusgrb** [oovoodev/Android-SDK-Sample#29]
Hi, I'm always getting crashes after setting targetSdkVersion to 23(android 6.0). Here is the stack trace:

FATAL EXCEPTION: main
Process: com.abc.app.debug, PID: 18298
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.abc.app.debug-1/lib/x86/libooVooSdk.so: has text relocations
   at java.lang.Runtime.loadLibrary(Runtime.java:372)
   at java.lang.System.loadLibrary(System.java:1076)
   at com.oovoo.sdk.api.ooVooClientImpl.<clinit>(Unknown Source)
   at com.abc.app.media.VideoCallManager.initialize(VideoCallManager.java:73)
   at com.abc.app.AbcApplication.initManagers(AbcApplication.java:132)
   at com.abc.app.AbcApplication.onCreate(AbcApplication.java:68)
   at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:326)
   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
   at android.app.ActivityThread.-wrap1(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

The exception is thrown when invoking the method `ooVooClient.isDeviceSupported()`.

Any help is much appreciated!

**Comment by moshea444** [comment]
I am having this issue as well with the Android SDK 2.3.0.117.  Did you have any luck?

**Comment by mateusgrb** [comment]
No =/

**Comment by NehaKushwah993** [comment]
Are you getting same issue while using sample app of oovoo?
