### ISSUE TITLE
AndroidRuntime FATAL EXCEPTION: main UnsatisfiedLinkError [DexPathList] couldn't find "libooVooSdk.so"

### ISSUE THREAD

**Issue by cubatertech** [oovoodev/Android-SDK-Sample#34]
Hi, Guys.

I,m facing a problem while integrating Android ooVoo SDK. I use android sample project but this working fine.
Issue occured when we use another native library like (GPUImage) then we get AndroidRuntime exception.
This is by due to some non-compatible ABi different intstruction sets according to chipset, e.g. x86, x86_64, arm64 etc.

Please see below my android studio logcat...

11-01 21:31:35.592 9884-9884/org.wysaid.cgedemo E/AndroidRuntime: FATAL EXCEPTION: main
Process: org.wysaid.cgedemo, PID: 9884
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-support-annotations-22.2.0_48d42d67d00135a75e70306d34b11dd7ec30ce10-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-oovoosdk_4531ffe1dd5def5c1caa3283b6a0d80f482ab6ee-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-internal_impl-22.2.0_fdc42a73f78ee5ffb862f820ae78091d9141bbc6-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-com.android.support-support-v4-22.2.0_a512187ef206ba5100fb4c5d1339b8e519a22e10-classes.dex", dex file "/data/data/org.wysaid.cgedemo/files/instant-run/dex/slice-com.android.support-appcompat-v7-22.2.0_abfec43db83da95661cd56be684ec007d549c0aa-classes.dex"],nativeLibraryDirectories=[/data/app/org.wysaid.cgedemo-1/lib/arm64, /vendor/lib64, /system/lib64, /vendor/lib64, /system/lib64]]] couldn't find "libooVooSdk.so"
  at java.lang.Runtime.loadLibrary(Runtime.java:367)
  at java.lang.System.loadLibrary(System.java:988)
  at com.oovoo.sdk.api.ooVooClientImpl.<clinit>(Unknown Source)
  at org.wysaid.AppController.onCreate(AppController.java:18)
  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4874)
  at android.app.ActivityThread.access$1500(ActivityThread.java:178)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loop(Looper.java:194)
  at android.app.ActivityThread.main(ActivityThread.java:5653)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
  
Above scenario is working file some devices, but maximum latest devices not supported.

Please help me because it is an serious issue for us. Thanks.

**Comment by cubatertech** [comment]
Issue solved. 
Use below link.
http://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libaries-on-64-bit-android-device

**Comment by eakraly** [comment]
Yep, ooVooSDK does not support 64 architecures
