### ISSUE TITLE
Cannot Join Conference in demo. App is stuck.

### ISSUE THREAD

**Issue by mydoal** [oovoodev/Android-SDK-Sample#7]
Samsung Galaxy Nexus Android 4.2.1 (API17)

LogCat:

04-23 13:32:35.804  22015-22015/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start receiver com.oovoo.core.phone.CallReceiver: java.lang.NullPointerException
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2383)
            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.oovoo.core.phone.AudioRouteManager.onPstnCallStarted(AudioRouteManager.java:806)
            at com.oovoo.core.phone.CallReceiver.hold(CallReceiver.java:30)
            at com.oovoo.core.phone.CallReceiver.onReceive(CallReceiver.java:113)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2376)
            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
04-23 13:34:11.952  22100-22100/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start receiver com.oovoo.core.phone.CallReceiver: java.lang.NullPointerException
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2383)
            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.oovoo.core.phone.AudioRouteManager.service(AudioRouteManager.java:763)
            at com.oovoo.core.phone.AudioRouteManager.onPstnCallEnded(AudioRouteManager.java:822)
            at com.oovoo.core.phone.CallReceiver.unhold(CallReceiver.java:40)
            at com.oovoo.core.phone.CallReceiver.onReceive(CallReceiver.java:81)
            at android.app.ActivityThread.handleReceiver(ActivityThread.java:2376)
            at android.app.ActivityThread.access$1500(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1310)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5039)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
            at dalvik.system.NativeStart.main(Native Method)
04-23 15:53:53.429      390-412/? W/ActivityManager﹕ No content provider found for permission revoke: file:///data/local/tmp/com.ooVoo.oovoosample
04-23 15:53:54.953      390-412/? W/ActivityManager﹕ No content provider found for permission revoke: file:///data/local/tmp/com.ooVoo.oovoosample
04-23 15:54:03.156      390-412/? W/PackageManager﹕ Code path for pkg : com.ooVoo.oovoosample changing from /data/app/com.ooVoo.oovoosample-2.apk to /data/app/com.ooVoo.oovoosample-1.apk
04-23 15:54:03.187      390-412/? W/PackageManager﹕ Resource path for pkg : com.ooVoo.oovoosample changing from /data/app/com.ooVoo.oovoosample-2.apk to /data/app/com.ooVoo.oovoosample-1.apk
04-23 15:54:03.593      390-412/? W/PackageManager﹕ Unknown permission android.permission.RECORD_VIDEO in package com.ooVoo.oovoosample
04-23 15:54:03.601      390-412/? W/PackageManager﹕ Unknown permission android.permission.BLUETOOTH_PRIVILEGED in package com.ooVoo.oovoosample
04-23 15:54:10.078  30237-30237/com.ooVoo.oovoosample W/ActivityThread﹕ Application com.ooVoo.oovoosample is waiting for the debugger on port 8100...
04-23 15:54:18.453  30237-30404/com.ooVoo.oovoosample W/ooVooSdkNative﹕ [Warning] GetMediaDeviceConfiguration: revision (8) of incoming configuration is less or equal then current (8) -> ignore.	[void ooVoo::Configuration::MediaDeviceConfig::parse(const string&)]
04-23 15:54:18.687  30237-30404/com.ooVoo.oovoosample W/PreviewUnit﹕ [Warning] SurfaceView is null
04-23 15:54:19.937      390-403/? W/ActivityManager﹕ Activity idle timeout for ActivityRecord{41655e48 u0 com.ooVoo.oovoosample/.Main.MainActivity}
04-23 15:54:19.968  30237-30404/com.ooVoo.oovoosample W/ooVooSdkNative﹕ [Warning] SetVideoParams failed! Capture device is not ready yet!	[ooVoo::ConferenceCoreError ooVoo::ConferenceVideoCore::SetVideoParams(ooVoo::device_shared_ptr, ooVoo::VideoType, const ooVoo::FrameSize&, int)]
04-23 15:54:20.164  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] Create VideoChannel at address = 1086626736 for name = Me
04-23 15:54:23.078  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] Create VideoChannel at address = 1356733328 with name = capture-camera
04-23 15:54:23.437  30237-30272/com.ooVoo.oovoosample W/ooVooSample﹕ No one listen OnCameraTurnedOn event..
04-23 15:54:23.578  30237-30404/com.ooVoo.oovoosample E/ooVooSdkNative﹕ [Error] Previous camera operation hasn't completed yet	[bool ooVoo::ConferenceVideoCore::IsCameraBusy()]
04-23 15:54:28.062  30237-30404/com.ooVoo.oovoosample W/CameraController﹕ [Warning] Cannot detect camera because it is already opened!
04-23 15:54:29.039  30237-30404/com.ooVoo.oovoosample W/PreviewUnit﹕ [Warning] WARNING! Codec video format qcif (176x144),  Framerate : 10fps is not supported by camera. Skipping it.
04-23 15:54:29.101  30237-30404/com.ooVoo.oovoosample E/PreviewUnit﹕ [Error] Could not find a video format of h264 that is supported by camera.
04-23 15:54:29.172  30237-30404/com.ooVoo.oovoosample E/PreviewUnit﹕ [Error] Camera set preview size error null
04-23 15:54:30.086  30237-30404/com.ooVoo.oovoosample W/ParticipantHolder﹕ [Warning] turnVideoOn -> turnVideoOn: No available GLView found for Participant
04-23 15:54:30.117  30237-30404/com.ooVoo.oovoosample W/ParticipantHolder﹕ [Warning] turnVideoOn -> turnVideoOn: current GLViews:
    com.ooVoo.oovoosample.Common.ParticipantHolder@41628088
04-23 15:54:30.468  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] Create VideoChannel at address = 1085772616 for name =
04-23 15:54:30.781  30237-30404/com.ooVoo.oovoosample W/ParticipantHolder﹕ [Warning] updateGLView -> turnVideoOn: current GLViews:
    updateGLView -> turnVideoOn:  [0] id: 2131361802 isOn: true isPreview: true isFullMode: false GLView: preview is ON, connected to () participant: Me () on viewId = 2131361802
04-23 15:54:30.929  30237-30404/com.ooVoo.oovoosample W/ooVooSdkNative﹕ [Warning] preview already turned ON...	[ooVoo::ConferenceCoreError ooVoo::ConferenceVideoCore::StartPreview(bool)]
04-23 15:54:31.062  30237-30404/com.ooVoo.oovoosample W/ParticipantHolder﹕ [Warning] turnVideoOn -> turnVideoOn: current GLViews already connected: id: 2131361802 isOn: true isPreview: true isFullMode: false GLView: preview is ON, connected to () participant: Me () on viewId = 2131361802
04-23 15:54:31.492  30237-30404/com.ooVoo.oovoosample W/ConferenceCore﹕ [Warning] turnCameraOn: Camera is already ON
04-23 15:54:31.562  30237-30404/com.ooVoo.oovoosample E/InternalEventsListener﹕ [Error] OnVideoTransmitTurnedOn error = InvalidOperation
04-23 15:54:31.836  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] ~VideoChannelPtr destroy preview at address = 1085772616
04-23 15:54:32.047  30237-30404/com.ooVoo.oovoosample W/ParticipantHolder﹕ [Warning] turnVideoOn -> turnVideoOn: current GLViews already connected: id: 2131361802 isOn: true isPreview: true isFullMode: false GLView: preview is ON, connected to () participant: Me () on viewId = 2131361802
04-23 15:54:32.054  30237-30404/com.ooVoo.oovoosample W/ooVooSdkNative﹕ [Warning] preview already turned ON...	[ooVoo::ConferenceCoreError ooVoo::ConferenceVideoCore::StartPreview(bool)]
04-23 15:54:32.976  30237-30404/com.ooVoo.oovoosample E/PreviewUnit﹕ [Error] Camera set preview size error null
04-23 15:54:33.000  30237-30404/com.ooVoo.oovoosample W/PreviewUnit﹕ [Warning] Cannot set video size 176x144! Camera reports actual size is 640x480
04-23 15:54:33.023  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] Create VideoChannel at address = 1479595408 with name = capture-camera
04-23 15:54:33.367  30237-30404/com.ooVoo.oovoosample W/VideoChannelPtr﹕ [Warning] ~VideoChannelPtr destroy capture-camera at address = 1356733328
04-23 15:54:34.351  30237-30404/com.ooVoo.oovoosample W/VideoRenderer﹕ [Warning] VideoRenderer(): setProgramParams: - wrong values width/height=0x0 texWidth/texHeight=0x0
04-23 15:54:34.375  30237-30404/com.ooVoo.oovoosample W/VideoRenderer﹕ [Warning] VideoRenderer(): setProgramParams:  frame is NULL
04-23 15:55:28.148  30237-30404/com.ooVoo.oovoosample W/CameraController﹕ [Warning] Cannot detect camera because it is already opened!
04-23 15:55:28.179  30237-30268/com.ooVoo.oovoosample E/ConferenceManager﹕ java.lang.IllegalStateException: Cannot detect camera. Camera is in use.
            at com.oovoo.core.device.camera.CameraController.detectSupportedFormats(CameraController.java:677)
            at com.oovoo.core.device.deviceconfig.CameraConfig.detectSupportedVideoFormats(CameraConfig.java:146)
            at com.oovoo.core.device.deviceconfig.CameraConfig.getVideoFormats(CameraConfig.java:51)
            at com.oovoo.core.ConferenceCore.InitCameraDevices(ConferenceCore.java:1015)
            at com.oovoo.core.ConferenceCore.updateDeviceConfig(ConferenceCore.java:1915)
            at com.oovoo.core.ConferenceCore.joinConference(ConferenceCore.java:1192)
            at com.oovoo.core.ConferenceCore.joinConference(ConferenceCore.java:1154)
            at com.ooVoo.oovoosample.ConferenceManager.doJoinSession(ConferenceManager.java:318)
            at com.ooVoo.oovoosample.ConferenceManager.onConferenceEvent(ConferenceManager.java:788)
            at com.ooVoo.oovoosample.ConferenceManager.access$000(ConferenceManager.java:51)
            at com.ooVoo.oovoosample.ConferenceManager$1.onHandleCommandMessage(ConferenceManager.java:175)
            at com.ooVoo.oovoosample.util.CommandQueued$1.handleMessage(CommandQueued.java:377)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at com.ooVoo.oovoosample.util.CommandQueued.run(CommandQueued.java:380)

**Comment by eakraly** [comment]
@mydoal,
Could you please provide a full log from the SDK?
